name = "MicroML"
uuid = "5687f320-7332-11e9-1d62-bd72802c4237"
authors = ["Chengyu HAN <cyhan.dev@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
